# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'managed': False, 'ordering': ('-id',)},
        ),
    ]
