# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-20 00:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20170507_0059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'managed': False, 'ordering': ('-creation_date',)},
        ),
    ]
