# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-20 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'formative',
                'ordering': ('-creation_date',),
            },
        ),
        migrations.CreateModel(
            name='FormativeHasQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'formative_has_question',
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_play', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('duration', models.TimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'play',
                'ordering': ('date_play',),
            },
        ),
    ]
