# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-21 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formative', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='play',
            options={'managed': False, 'ordering': ('creation_play',)},
        ),
    ]
