# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 01:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formative', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formative',
            options={'managed': False, 'ordering': ('-creation_date',)},
        ),
    ]
