# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formative', '0002_auto_20170507_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('duration', models.TimeField(blank=True)),
            ],
            options={
                'managed': False,
                'ordering': ('date',),
                'db_table': 'play',
            },
        ),
    ]
