# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-22 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formative', '0002_auto_20170821_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='play',
            options={'managed': False, 'ordering': ('creation_play', 'start_play')},
        ),
    ]
