# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formative', '0003_auto_20170822_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formativehasquestion',
            options={},
        ),
    ]
