# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-20 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formative', '0003_play'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='play',
            options={'managed': False, 'ordering': ('date_play',)},
        ),
    ]
