# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formative', '0004_auto_20170831_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formativehasquestion',
            options={'managed': False},
        ),
    ]
