# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formative', '0005_auto_20170831_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formativehasquestion',
            options={'managed': False, 'ordering': ('order',)},
        ),
    ]
