"""
Django settings for play project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os, json

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Import credentials for file credentials.json
credentials = json.load(open(os.path.join(BASE_DIR, 'play/credentials.json')))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = credentials['secret_key']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = credentials['allowed_hosts']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.formative',
    'apps.teacher',
    'apps.question',
    'apps.play',
    'apps.student',
    'apps.course',
    'apps.login',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'play.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'play.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

database = credentials['database']
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': database['name'],
        'USER': database['user'],
        'PASSWORD': database['password'],
        'HOST': database['host'],
        'PORT': database['port'],
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# Authentication backends
# https://docs.djangoproject.com/en/1.10/topics/auth/customizing/

AUTHENTICATION_BACKENDS = ( 
    #'play.login.LoginBackend',
    'django.contrib.auth.backends.ModelBackend',
    )

LOGIN_URL = '/fama'

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'Chile/Continental'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/fama/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'preguntas'),
    )

# Celery configurations options
CELERY_BROKER_URL = 'amqp://localhost'

# Logging Django
# https://docs.djangoproject.com/en/1.10/topics/logging/
from .logger import LOGGING

#LOGGING = {
#    'version': 1,
#    'disable_existing_loggers': False,
#    'formatters': {
#        'verbose': {
#            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
#        },
#    },
#    'handlers': {
#        'file_debug': {
#            'level': 'DEBUG',
#            'class': 'logging.FileHandler',
#            'formatter': 'verbose',
#            'filename': os.path.join(BASE_DIR, 'logs/django_debug.log')
#        },
#        'file_info': {
#            'level': 'INFO',
#            'class': 'logging.FileHandler',
#            'filename': os.path.join(BASE_DIR, 'logs/django_info.log')
#        },
#        'file_error': {
#           'level': 'ERROR',
#            'class': 'logging.FileHandler',
#            'filename': os.path.join(BASE_DIR, 'logs/django_error.log')
#        },
#    },
#    'loggers': {
#        'django': {
#            'handlers': ['file_debug'],
#            'level': 'DEBUG',
#            'propagate': True,
#        },
#    },
#}

