# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 23:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(blank=True, max_length=40, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('share', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=9, null=True)),
                ('url', models.CharField(blank=True, max_length=40, null=True)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('creation_date', models.DateTimeField(blank=True)),
                ('last_login', models.DateTimeField(blank=True)),
            ],
            options={
                'managed': False,
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='TeacherHasQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'teacher_has_question',
            },
        ),
    ]
