# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-20 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'managed': False, 'ordering': ('-creation_date',)},
        ),
        migrations.AlterModelOptions(
            name='teacherhasquestion',
            options={'managed': False, 'ordering': ('-incorporation_date',)},
        ),
    ]
