# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 04:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20170507_0346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherhasquestion',
            options={'managed': False, 'ordering': ('-incorporation_date',)},
        ),
    ]
