# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_reply', models.DateTimeField()),
                ('stop_reply', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'reply',
            },
        ),
    ]
